### ISSUE TITLE
Error in php 7.4

### ISSUE THREAD

**Issue by zahovicS** [leafsphp/mvc-core#10]
`syntax error, unexpected '|', expecting variable (T_VARIABLE) in C:\laragon\www\sistema-venta-v1\vendor\leafs\mvc-core\src\globals\functions.php on line 23`

Version v1.3.0 - 1 Sep 2023 causes an error.

`function view(string $view, array|object $data = [])`

v1.3.0-beta - 24 Aug 2023 Works fine

`function view(string $view, array $data = [])`

**Comment by mychidarko** [comment]
Will be releasing a fix soon @zahovicS
