### ISSUE TITLE
MVC setup for production getting Vite manifest not found at: /build/build/manifest.json

### ISSUE THREAD

**Issue by juanulis3s** [leafsphp/mvc-core#13]
**Describe the bug**
I am using leaf MVC.
The app is ready and I am trying to setting this up for deploy on a cpanel server.
When setting up the app with `leaf view:build` it seems something is failing.

**To Reproduce**

1. Setup an MVC app
2. Setup ENV production variables
3. Execute command `leaf view:build`
4. Upload to server and you will see `Vite manifest not found at: /build/build/manifest.json`

Is there a way to setup the env file for production?
Am I missing a step?

**Comment by fatherofinvention** [comment]
I'm facing the same error. Hi @mychidarko this was reported 2 months ago, have you had a chance to look into it yet?

**Comment by fatherofinvention** [comment]
Update: I was wrong, this was actually reported **over 5 months ago** and no update from anyone on the core team about it yet:

https://github.com/leafsphp/mvc-core/issues/15

**Comment by mychidarko** [comment]
Checking this out

**Comment by mychidarko** [comment]
A new version will be released to fix this issue soon. You can fix it for now in your codebase by adding this snippet to your `public/index.php` file:

```php
\Leaf\Vite::config('build', PublicPath('', false));
```

**Comment by mychidarko** [comment]
Updating leafs/vite and leafs/mvc-core should now completely fix this issue
