### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by dedychaidir** [leafsphp/mvc-core#3]
I was just testing this framework by calling index point using user model in UsersController like this:
`    public function index() {
        $users = User::find()->all();
        response(["response" => $users]);
    }`

but it give me an error. 
stack traces: 
`Leaf\Exceptions\ErrorException
…\vendor\leafs\mvc-core\src\Database.php30`

and the line 30 is:
`static::$config['connections'][$connection]`

**Comment by mychidarko** [comment]
Hi @dedychaidir, do you still have this issue?
